import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useState} from "react"
import Card from "../components/Card"

const Home: NextPage = () => {
  const [difficulty, setDifficulty] = useState(1)
  let cards = [] 
  for(let i = 0; i<15; i++) cards.push(<Card key={i}/>)

  return (
    <div className={styles.container}>
      <Head>
        <title>Test your memory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav><button>easy</button><button>medium</button><button>hard</button></nav>
        <div>60:00</div>
        <section className={styles.grid_layout}>
        {cards}
        </section>
      </main>
    </div>
  )
}

export default Home
